### ISSUE TITLE
CUDA out of memory, and others

### ISSUE THREAD

**Issue by RinStrawberry** [cyberofficial/Synthalingua#8]
Windows 10
Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz   4.01 GHz
16.0 GB
64-bit OS
NVIDIA GeForce GTX 960

Switching to "--device cpu" avoids the error, and applying the fix for "[WinError 2] The system cannot find the file specified" solves the other issue but transcribing JP language is way too slow and sometimes outputs unknown signs instead of English so I'd like to use device Cuda to see if it significantly improves it.

Using device: Cuda (default)
--ram 12gb --record_timeout 2 --language ja --energy_threshold 250

![da](https://user-images.githubusercontent.com/129454785/229113144-7506f32c-0955-4909-ba0b-5064f9ff3daa.png)

Using device: cpu
--ram 12gb --record_timeout 2 --device cpu --language ja --energy_threshold 250

![err](https://user-images.githubusercontent.com/129454785/229113178-58a30df8-36aa-44d1-ac48-c1e5ca06089d.png)

I noticed that in using device: Cuda, it gets error- "Failed to load fine-tuned model." Deleting the model then re-installing it through livetranslation.bat causes this before quickly closing.

![err2](https://user-images.githubusercontent.com/129454785/229114983-4c481e31-3625-4c3e-8bca-bedf4efbc89b.png)

**Comment by cyberofficial** [comment]
Hello, thanks for making a report, I will look into this.

**Comment by RinStrawberry** [comment]
When trying to access the link, it says Page not found.

**Comment by cyberofficial** [comment]
> When trying to access the link, it says Page not found.

try again now

**Comment by RinStrawberry** [comment]
I downloaded the new version. This is what I got (after old fine-tuned model was removed and code set back to 12 gb ram when it first processed a bit telling me the model couldn't be found, and the ram was too small that it was downloading compressed model instead).

![new-error](https://user-images.githubusercontent.com/129454785/229254821-5215a87d-5649-47f6-89c3-0f461f687021.png)

![new-error2](https://user-images.githubusercontent.com/129454785/229254833-d8812d9f-cf18-4fd1-ba50-3590577b1e7e.png)

In case these can help,

![daa](https://user-images.githubusercontent.com/129454785/229254864-8b7bcca2-5f41-40c7-87be-472694bc65ab.png)

![ddd](https://user-images.githubusercontent.com/129454785/229254870-6bbe8ce6-fec5-4d9b-bb32-5fb28fee1009.png)

**Comment by cyberofficial** [comment]
https://github.com/cyberofficial/Synthalingua/archive/refs/heads/master.zip

Hello, I've updated the program add additional checks. If this doesn't work, I have a few more things to try out.

Thank you for being interested in the app, stuff like this will help out in the long run.

**Comment by RinStrawberry** [comment]
This is what I get (--ram 12gb --non_english --translate):

![error](https://user-images.githubusercontent.com/129454785/229323456-6ea2ca84-35ac-465b-8745-b888d4920652.png)

Thank you as well/

**Comment by cyberofficial** [comment]
Hello, https://github.com/cyberofficial/Synthalingua/archive/refs/heads/dev-testing.zip
See if this patch helps or not.

**Comment by cyberofficial** [comment]
Okay, I *pray* *i hope* https://github.com/cyberofficial/Synthalingua/archive/refs/heads/master.zip

This fixes the errors.

**Comment by RinStrawberry** [comment]
I bring bad news.

![error2](https://user-images.githubusercontent.com/129454785/229330777-312ccffa-9e49-407a-8b59-798c88fa5cea.png)

**Comment by cyberofficial** [comment]
Your version is outdated again, I updated it a little bit ago.
<img width="1191" alt="opera_Ky8r5PJyxS" src="https://user-images.githubusercontent.com/19499442/229331036-2171500a-2b9a-45e6-b10f-da465f9a810b.png">

also seems like you are using 6gb vram option when you have 4gb

**Comment by RinStrawberry** [comment]
I was going to message sooner concerning that but wanted to test it more. Because coincidentally, I re-installed again and this time didn't touch anything from the default commands (4gb vram). It worked!

![raz](https://user-images.githubusercontent.com/129454785/229331769-fefde1cf-d9d9-4d7c-a09b-0b1315e4321c.png)

Didn't realize my vram was lower.

![test](https://user-images.githubusercontent.com/129454785/229331799-6c314bd0-7dc2-4ec5-8c1b-3788642af63a.png)

The translation speed is noticeably faster this time but the translator is still having a hard time. I'll update and continue trying to make it comfortably work.

Are those question mark symbols normal?

**Comment by cyberofficial** [comment]
> Are those question mark symbols normal?
Yes, just means your windows install doesn't have the special character's installed. Doesn't really hurt anything.

https://support.microsoft.com/en-us/windows/install-a-language-for-windows-ccd853d3-9ecd-7da7-9ef0-72b4a055410a

You can do this if you reallllyyyy want to see the JP Lettering.

**Comment by RinStrawberry** [comment]
I see. Thank you lots! For creating this tool and assisting me until it all works. I'll keep up-to-date with all the improvements you plan on doing.

![razx](https://user-images.githubusercontent.com/129454785/229332944-f778d031-ffcd-48f1-96ab-5a4c19798fe1.png)
